---
- name: A demo of modifying a registry file
  hosts: localhost
  gather_facts: false
  vars:
    regfile_path: data/win10-small.reg
  tasks:
    - name: Test cases for modifying registry file.
      regedit:
        registry_filename: "{{ regfile_path }}"
        hkey: "{{ item.hkey }}"
        key:  "{{ item.key | default(omit) }}"
        val:  "{{ item.val | default(omit) }}"
        verb: "{{ item.verb }}"
        # If verb: upd, then set the following keys accordingly
        new_hkey: "{{ item.new_hkey | default(omit) }}"
        new_key:  "{{ item.new_key  | default(omit) }}"
        new_val:  "{{ item.new_val  | default(omit) }}"
      register: result
      with_items:
        # =========================================================================
        # Test Case ADD-01: Add an HKEY
        # =========================================================================
        - {
            verb: add,
            hkey: '[HKEY_LOCAL_MACHINE\SOFTWARE\DummyHKEY]',
        }
        # =========================================================================
        # Test Case ADD-02: Add a kv-pair to an HKEY where value is a "string"
        # =========================================================================
        - {
            verb: add,
            hkey: '[HKEY_LOCAL_MACHINE\SOFTWARE\DummyHKEY]',
            key: FullName,
            val: '"Harlequin Joost"',
        }
        # =========================================================================
        # Test Case ADD-03: Add a kv-pair to an HKEY where value is a bare dword
        # =========================================================================
        - {
            verb: add,
            hkey: '[HKEY_LOCAL_MACHINE\SOFTWARE\DummyHKEY]',
            key: FullBareWord,
            val: 'dword:11111111',
        }
        # =========================================================================
        # Test Case CHK-01: Check if an HKEY exists
        # =========================================================================
        - {
          verb: chk,
          hkey: '[HKEY_LOCAL_MACHINE\SOFTWARE]',
        }
        # =========================================================================
        # Test Case CHK-02: Check if an HKEY kv-pair exists (is set)
        # =========================================================================
        - {
          verb: chk,
          hkey: '[HKEY_LOCAL_MACHINE\SOFTWARE\Common Files]',
          key: CloudConnectorConfigDir,
          val: '"/var/opt/vendor/install/CloudConnectorConfig"',
        }
        # =========================================================================
        # Test Case CHK-03: Check return of non-existing HKEY
        # =========================================================================
        - {
          verb: chk,
          hkey: '[HKEY_LOCAL_MACHINE\BCD00000000\DoesNotExist]',
        }
        # =========================================================================
        # Test Case DEL-01: Delete an HKEY (and any direct kv-pairs)
        # =========================================================================
        - {
          verb: del,
          hkey: '[HKEY_LOCAL_MACHINE\BCD00000000\DeleteMe]',
        }
        # =========================================================================
        # Test Case DEL-02: Delete an HKEY kv-pair
        # =========================================================================
        - {
          verb: del,
          hkey: '[HKEY_LOCAL_MACHINE\BCD00000000\DeleteMe2]',
          key: TreatAsSystem
        }
        # =========================================================================
        # Test Case DEL-03: Delete an HKEY kv-pair only if the value is as specified
        # =========================================================================
        - {
          verb: del,
          hkey: '[HKEY_LOCAL_MACHINE\BCD00000000\DeleteMe2]',
          key: System,
          val: 'dword:00000001'
        }
        # =========================================================================
        # Test Case UPD-01: Update HKEY path
        # =========================================================================
        - {
          verb: upd,
          hkey: '[HKEY_LOCAL_MACHINE\BCD00000000\UpdateMe]',
          new_hkey: '[HKEY_LOCAL_MACHINE\HelloWorld\UpdateMe]',
        }
        # =========================================================================
        # Test Case UPD-02: Update key
        # =========================================================================
        - {
          verb: upd,
          hkey: '[HKEY_LOCAL_MACHINE\BCD00000000\UpdateMe2]',
          key: NodeJS,
          new_key: nodejs,
        }
        # =========================================================================
        # Test Case UPD-03: Update value
        # =========================================================================
        - {
          verb: upd,
          hkey: '[HKEY_LOCAL_MACHINE\BCD00000000\UpdateMe2]',
          key: nodejs,
          new_val: '"/var/opt/vendor/install/NodeJS/bin/node"',
        }
