---
- name: Test cases for updating a registry file
  hosts: localhost
  gather_facts: false
  vars:
    regfile1_path: fiddle/minimsi-1.reg
    regfile2_path: fiddle/minimsi-2.reg
  tasks:
    # =========================================================================
    # Test Case UPD-01.1: Update HKEY path where HKEY path exists new HKEY
    # =========================================================================
    - name: 'Test Case UPD-RW.1: user owned'
      regedit:
        registry_filename: "{{ regfile1_path }}"
        verb: add
        hkey: '[HKEY_LOCAL_MACHINE\SOFTWARE\MicroStrategy\Common Files]'
        key: TrustStorePassphrase
        val: '""'
      register: result
    - debug:
        msg: "{{ result.message }} - expected result: 'ok'"

    # =========================================================================
    # Test Case UPD-01.2: Update HKEY path where HKEY path exists new HKEY
    # =========================================================================
    - name: 'Test Case UPD-RW.2: root owned'
      regedit:
        registry_filename: "{{ regfile2_path }}"
        verb: add
        hkey: '[HKEY_LOCAL_MACHINE\SOFTWARE\MicroStrategy\Common Files]'
        key: TrustStorePassphrase
        val: '""'
      register: result
    - debug:
        msg: "{{ result.message }} - expected result: 'ok'"
...
